name: 下载 LiteLLM 镜像为 tar

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取官方镜像
        run: docker pull docker.litellm.ai/berriai/litellm:main-stable

      - name: 导出为 tar 文件
        run: docker save -o litellm-new.tar docker.litellm.ai/berriai/litellm:main-stable

      - name: 上传为可下载产物
        uses: actions/upload-artifact@v4
        with:
          name: litellm-image
          path: litellm-new.tar
